# Site settings
title: Bob Profile
email: joe@00bbq.com
description: > # this means to ignore newlines until "baseurl:"
  Learn to use GitHub pages with Wheelhouse.io and Patchwork!
baseurl: http://iMillJoe.github.io
url: "http://wheehouseio.github.io"
twitter_username: WheelhouseIO
github_username:  wheelhouseio
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
